# Site settings
title: "Adunbi Moses' Portfolio"
description: "A portfolio showcasing my skills, projects, and professional experience."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://artkinx.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# theme: minima
remote_theme: mmistakes/minimal-mistakes@4.26.2

# Author settings
# author:
#   name: "Adunbi Moses"
#   email: "your-email@example.com"
#   twitter_username: "your-twitter-username"
#   github_username: "your-github-username"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
#   - jekyll-seo-tag

# # Permalinks
# permalink: /:categories/:year/:month/:day/:title/

# # Navigation
# navigation:
#   - title: "Home"
#     url: "/"
#   - title: "Skills"
#     url: "/#skills"
#   - title: "Projects"
#     url: "/#projects"
#   - title: "Professional Experience"
#     url: "/#professional-experience"
#   - title: "Interests"
#     url: "/#interests"
#   - title: "Blog"
#     url: "/#blog"
#   - title: "Contact"
#     url: "/#contact"
#   - title: "Social Media"
#     url: "/#social-media"
#   - title: "Design Portfolio"
#     url: "/#design-portfolio"
